### ISSUE TITLE
file transfer tools .... Transfer.py 

### ISSUE THREAD

**Issue by stefaniaspagnolo** [PADME-Experiment/padme-fw#178] opened 2019-07-18 10:18 UTC
Ciao, 
I tried 
 nohup ./TransferRun.sh -R run_0000000_20190228_131527  -S LNF -d /nfs/kloe/einstein3/padme/data/rawdata/run_0000000_20190228_131527_fullds/ -j 10 >getRun_20190228_131527.log &
with the develop version and I got the following error messages: 

Usage: ./TransferRun.sh -r run [-S src_site] [-D dst_site] [-L dst_dir] [-y year] [-j jobs] [-h]
Available source sites: CNAF LNF LNF2
Available destination sites: CNAF LNF LNF2 LOCAL
Default: copy from CNAF to LOCAL

I guess the problem is the -d option (documented in the wiki).... 
How can this be solved ? 
Stefania

**Comment by eleonardi** [comment] 2019-07-18 10:41
Ciao Stefania.Usa il package padme-cdr invece di padme-fw.Emanuele Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Stefania Spagnolo <notifications@github.com> Data: 18/07/19  12:18  (GMT+01:00) A: PADME-Experiment/padme-fw <padme-fw@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: [PADME-Experiment/padme-fw] file transfer tools .... Transfer.py  (#178) Ciao,
I tried
nohup ./TransferRun.sh -R run_0000000_20190228_131527  -S LNF -d /nfs/kloe/einstein3/padme/data/rawdata/run_0000000_20190228_131527_fullds/ -j 10 >getRun_20190228_131527.log &
with the develop version and I got the following error messages:
Usage: ./TransferRun.sh -r run [-S src_site] [-D dst_site] [-L dst_dir] [-y year] [-j jobs] [-h]
Available source sites: CNAF LNF LNF2
Available destination sites: CNAF LNF LNF2 LOCAL
Default: copy from CNAF to LOCAL
I guess the problem is the -d option (documented in the wiki)....
How can this be solved ?
Stefania

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PADME-Experiment/padme-fw/issues/178?email_source=notifications\u0026email_token=AC5G6XTK2ZLRQ77A7A6BGMLQAA7OPA5CNFSM4IEZFNH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G763X2Q",
"url": "https://github.com/PADME-Experiment/padme-fw/issues/178?email_source=notifications\u0026email_token=AC5G6XTK2ZLRQ77A7A6BGMLQAA7OPA5CNFSM4IEZFNH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G763X2Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by eleonardi** [comment] 2019-07-24 09:40
Solved by using gfal-stat instead of gfal-ls to get filesize

**Closed by eleonardi** 2019-07-24 09:40 UTC
